name: unittest CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: make test binary file
      run: make test -j
    - name: run test
      run: ./ircserv_test
    - name: Check Status
      if: failure()
      run: exit 1
